# Generated by Django 6.1 on 2026-09-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("triage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicaldocument",
            name="emergency_reasoning",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="is_emergency_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="triage_check_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="triage.checkin",
            ),
        ),
    ]
