# Generated by Django 6.1 on 2026-09-19 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0003_patient_consent_given_at_patient_guardian_consent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AyurvedaAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("FINALIZED", "Finalized")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VEGETARIAN", "Vegetarian"),
                            ("EGGETARIAN", "Eggetarian"),
                            ("NON_VEGETARIAN", "Non-vegetarian"),
                            ("VEGAN", "Vegan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meal_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REGULAR", "Regular meal timing"),
                            ("IRREGULAR", "Irregular meal timing"),
                            ("FREQUENT_SNACKING", "Frequent snacking"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "water_intake",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("ADEQUATE", "Adequate"),
                            ("EXCESSIVE", "Excessive"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "taste_preferences",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of preferred rasas, e.g. SWEET,SALTY",
                        max_length=100,
                    ),
                ),
                ("sleep_duration_hours", models.FloatField(blank=True, null=True)),
                (
                    "sleep_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOUND", "Sound"),
                            ("DISTURBED", "Disturbed"),
                            ("INSOMNIA", "Insomnia"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "bowel_habits",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REGULAR", "Regular"),
                            ("IRREGULAR", "Irregular"),
                            ("CONSTIPATED", "Constipated"),
                            ("LOOSE", "Loose"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "physical_activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SEDENTARY", "Sedentary"),
                            ("MODERATE", "Moderate"),
                            ("ACTIVE", "Active"),
                            ("VERY_ACTIVE", "Very active"),
                        ],
                        max_length=15,
                    ),
                ),
                ("addictions", models.TextField(blank=True)),
                (
                    "occupation_stress_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ahara_vihara_notes", models.TextField(blank=True)),
                (
                    "vikriti_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                            ("VATA_PITTA", "Vata-Pitta"),
                            ("PITTA_KAPHA", "Pitta-Kapha"),
                            ("VATA_KAPHA", "Vata-Kapha"),
                            ("TRIDOSHA", "Tridosha (Sama)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("vikriti_notes", models.TextField(blank=True)),
                (
                    "sara_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRAVARA", "Pravara (excellent)"),
                            ("MADHYAMA", "Madhyama (moderate)"),
                            ("AVARA", "Avara (poor)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sara_notes", models.TextField(blank=True)),
                (
                    "samhanana_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRAVARA", "Pravara (excellent)"),
                            ("MADHYAMA", "Madhyama (moderate)"),
                            ("AVARA", "Avara (poor)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("samhanana_notes", models.TextField(blank=True)),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                (
                    "pramana_assessment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADEQUATE", "Adequate proportion"),
                            ("INADEQUATE", "Inadequate proportion"),
                        ],
                        max_length=15,
                    ),
                ),
                ("pramana_notes", models.TextField(blank=True)),
                (
                    "satmya_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRAVARA", "Pravara (excellent)"),
                            ("MADHYAMA", "Madhyama (moderate)"),
                            ("AVARA", "Avara (poor)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("satmya_notes", models.TextField(blank=True)),
                (
                    "sattva_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRAVARA", "Pravara (excellent)"),
                            ("MADHYAMA", "Madhyama (moderate)"),
                            ("AVARA", "Avara (poor)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sattva_notes", models.TextField(blank=True)),
                (
                    "abhyavaharana_shakti",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRAVARA", "Pravara (excellent)"),
                            ("MADHYAMA", "Madhyama (moderate)"),
                            ("AVARA", "Avara (poor)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "agni_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAMA", "Sama Agni (balanced)"),
                            ("VISHAMA", "Vishama Agni (irregular)"),
                            ("TIKSHNA", "Tikshna Agni (sharp/excessive)"),
                            ("MANDA", "Manda Agni (weak/slow)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ahara_shakti_notes", models.TextField(blank=True)),
                (
                    "vyayama_shakti_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRAVARA", "Pravara (excellent)"),
                            ("MADHYAMA", "Madhyama (moderate)"),
                            ("AVARA", "Avara (poor)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("vyayama_shakti_notes", models.TextField(blank=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="patients.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayurveda_assessments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrakritiProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_frame",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "hair_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "appetite_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sleep_pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mental_temperament",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                        ],
                        max_length=10,
                    ),
                ),
                ("self_report_notes", models.TextField(blank=True)),
                ("self_report_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prakriti_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VATA", "Vata"),
                            ("PITTA", "Pitta"),
                            ("KAPHA", "Kapha"),
                            ("VATA_PITTA", "Vata-Pitta"),
                            ("PITTA_KAPHA", "Pitta-Kapha"),
                            ("VATA_KAPHA", "Vata-Kapha"),
                            ("TRIDOSHA", "Tridosha (Sama)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="patients.doctor",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prakriti_profile",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
